services:
  FreezyBee\DataGridBundle\DataGridFactory:
    autowire: true

  FreezyBee\DataGridBundle\Export\:
    resource: '../../Export/*'
    autowire: true
    tags: ['datagrid.exporter']

  FreezyBee\DataGridBundle\Twig\DataGridExtension:
    autowire: true
    tags: ['twig.extension']

  FreezyBee\DataGridBundle\Controller\DataGridController:
    autowire: true
    tags: ['controller.service_arguments']

  FreezyBee\DataGridBundle\Export\DataGridExporterInterface: '@FreezyBee\DataGridBundle\Export\ChainExporter'

  JMS\Serializer\SerializerInterface:
    autowire: true
